version: '2'
services:
  node:
    image: node:alpine
    user: ${USER_ID}
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:z
    ports:
      - 127.0.0.1:5858:5858
    environment:
      - NODE_ENV=development
    command:
      - npm test
